### ISSUE TITLE
Error on Windows when input is redirected

### ISSUE THREAD

**Issue by CalculonPrime** [anseki/readline-sync#106]
npm ERR! npm install test-readline-sync: c:\ws\src\node_file.cc:1724: Assertion `(argc) == (5)' failed.
npm ERR!  1: 00007FF71147046F napi_wrap+109311
npm ERR!  2: 00007FF711415156 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfElementsOffset+333
02
npm ERR!  3: 00007FF7114154D1 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap,2>::NumberOfElementsOffset+341
93
npm ERR!  4: 00007FF7114093B7 v8::base::CPU::has_sse+13095
npm ERR!  5: 00007FF711C8FC2F v8::internal::Builtins::builtin_handle+321439
npm ERR!  6: 00007FF711C8F1C4 v8::internal::Builtins::builtin_handle+318772
npm ERR!  7: 00007FF711C8F4B7 v8::internal::Builtins::builtin_handle+319527

node: v14.16.1
npm: 7.9.0

I see that you keep closing this same crash report:
https://github.com/anseki/readline-sync/issues/94
https://github.com/anseki/readline-sync/issues/98

Why did you do that?  Unless readline-sync is abandoned, you need to fix crashes!  Otherwise I will have to replace it as a dependency.

**Comment by anseki** [comment]
Hi @CalculonPrime, thank you for the comment.
Do you mean that you want to redirect input?
If so, `fs.c` doesn't work now.
Also, you don't need this module now because Node.js already implemented the features. I think that the module have already finished its part at that time.
You can use Readline (not readlineSync) or another module now, it's better choice.

**Comment by CalculonPrime** [comment]
Well readline isn't synchronous, so I'd have to wrap it, and more importantly, readline doesn't support hiding password typing like readline-sync.  The key API I'm using is readline-sync.question().

**Comment by anseki** [comment]
If you don't want to wrap that (but you can wrap it easily) or you want something like utility method, you can use another module instead.

**Comment by CalculonPrime** [comment]
What other module?  I've tried using async/await around the built-in readline question() API and it doesn't block the calling function.  How do I get synchronous readline?

**Comment by anseki** [comment]
I don't know what module you want but you can search modules in https://www.npmjs.com/ and find modules that read via TTY such as [prompts](https://www.npmjs.com/package/prompts).
See document for `async/await`: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

**Comment by CalculonPrime** [comment]
I know how to search modules.  I'm not aware of any that replace readline-sync.  As far as async/await, that isn't a replacement either, as it requires the entire hierarchy of calling functions to be made async.

**Comment by anseki** [comment]
Sorry, I don't know what module you want and problem about `async/await` in your app.
However, `async/await` and `Promise` are very important for JavaScript.
In general, module such as the prompts and `async/await` can be used instead of readlineSync. I don't know why you can't that because I don't know what you want to do.

**Comment by anseki** [comment]
You had better search modules by yourself if you know how to that and you don't like the module that I told.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
