### ISSUE TITLE
Assignment of query and response pipes

### ISSUE THREAD

**Issue by tk44** [anseki/readline-sync#12]
I have a child process created by child_process.exec(), and the main process needs to query the child on stdin.   The parent needs to read the response synchronously, which comes back on stdout.
   Could you add a way to re-assign pipes (including stdio[3] and above preferably) as options?

**Comment by anseki** [comment]
Hi tk44
Sorry but, I can't understand your post perfectly, because my English is no good.
Do you mean that the child process calls `question()` method? And, the parent process can't get some output of child process? (e.g. `process.stdout.write(readlineSync.question('Name? :'))`). Or, the child process can't read from TTY?
Can I see sample code?
BTW, stdio[3] is not needed. That reads from fd:0 (STDIN).

**Comment by tk44** [comment]
Sorry if I confused you.   The normal way to talk to a child process under Node is to send  query/question/request through the parent's std'in' and receive responses on the parent's std'out'.  First two examles on:
http://www.graemeboy.com/node-child-processes
demonstrate this by displaying parent's stdout on the console to show what the parent received from the child.
  A parent process normally uses stdout for outgoing and stdin for incoming messages, but the communication with a child process normally use them in the reverse order, so that the child would not tie-up the two pipes.  This way, the parent can send messages to the outside world through stdout, and can use stdin to send messages 'to' the child, as they are both two-way i/o channels.

When the parent sends a query to the child, it's like process.'stdin'.write(readlineSync.question('Name')), and the response comes back on the parent's std'out', like process.'stdout'.on() for the parent to read it.  Parent can read child.stdout directly and can write to child.stdin directly, but starting and killing the child process are normally not under control by the data reading functions.

So what I am asking for is an option like 'reverse_pipes' to flip stdin (for questions) and stdout (for answers), or an optional free assignment like "query_ch = stdio[0]" and "response_ch = stdio[2]".  (What is the default assignment for stdio[3] (assigned to stdin) and above, and where Node would go in the future (customFd has been removed, but more use of child_process --hence the requirement for more i/o channels-- seem certain) is outside of the scope here.)   Have I made myself clear enough?

**Comment by anseki** [comment]
I think that you might have misunderstood about STDIN/OUT...
You said "talk to a child process under Node via parent's STDIN/OUT", right?
But, the standard streams are assigned to each process. The parent's STDIN/OUT usually are TTY. *Not only Node.*
Those usually are given by the caller. The parent's standard streams have absolutely nothing to do with the own standard streams for the child. And, the standard streams of a process that is started by shell are TTY(console) as default.

So, parent's STDIN/OUT you said is TTY, not child. Therefore that STDIN is *NOT* used to send messages to the child. Also, that STDOUT is *NOT* used to read child's response. (That is TTY, but an error will be thrown, because that is not writable. The your `process.stdin.write()` means "Write something to the keyboard".)
The parent assigns something as child's STDIN, and the standard streams are chosen by you, not readlineSync, but of course you don't have to change those channels for talking to a child. And also, of course it's not only Node.
You can access the standard streams of the child via `child.stdin/out/err`.
http://nodejs.org/api/child_process.html#child_process_child_stdin

For example:

`parent.js`
```js
var child = require('child_process').spawn('node', ['child.js']),
  res = '';
// Write to child's STDIN, not parent's STDIN. (own one)
child.stdin.write('Hello', function() { child.stdin.end(); });
// Read from child's STDOUT, not parent's STDOUT. (own one)
child.stdout.on('data', function(chunk) { res += chunk; });
child.on('close', function (code) {
  // Write to own STDOUT.
  console.log('Exited Code: ' + code);
  console.log('Child said: ' + res);
});
```

`child.js`
```js
var input = '';
process.stdin.resume();
// Read from STDIN, not STDOUT.
process.stdin.on('data', function(chunk) { input += chunk; });
process.stdin.on('end', function() {
  // Write to STDOUT, not STDIN.
  console.log('I am a child, I received: ' + input);
  process.exit();
});
```

```shell
node parent.js
Exited Code: 0
Child said: I am a child, I received: Hello
```

So, do you want to use readlineSync in a child process?
Try this:

`parent.js`
```js
require('child_process')
  .spawn('node', ['child.js'], {stdio: 'inherit'})
  .on('close', function (code) {
    console.log('Exited Code: ' + code);
  });
```

`child.js`
```js
console.log('ANSWER: ' + require('readline-sync').question('Name? :'));
```

**Comment by tk44** [comment]
Thanks for the message.  I appreciate your time and effort on this.
Many of the things you said are correct.  As I said above, "Parent can read child.stdout directly and can write to child.stdin directly", so your first parent.js example works as you expect it.

However, suppose your child process is designed to kill itself right after it sends the response message "I am a child, I received: Hello" (probably because receiving one (or 20 or 10000) query and responding with one (or 20 or 10000) answer is the purpose of the child worker threads that are required to do a lot of CPU intensive processing in coming up with the response).

In this case, right after the (last) data is sent, the child process dies, leaving the sent data and parent process unstable because the 'child' object disappears mid-process, including child.stdio.  Further imagine if there are 10 or more worker threads working for the parent process.  The parent needs to monitor 10 or more channels for .on() events in this case.

This is why replacing the lines with:
// Write to parent's STDIN, not child's STDIN.
stdin.write('Hello', function() { process.stdin.end(); });
// Read from parent's STDOUT, not child's STDOUT.
stdout.on('data', function(chunk) { res += chunk; });

is usually a better practice because parent's own stdio don't disappear, and this is the way demonstrated on the child_process URL I mentioned above (yes, without any background info and reasons on pipe assignments :).  Because the default pipe assignments on child_process is child.stdout to parent stdout, and parent stdin to child.stdin, the code with the above replacement normally works.   And this way, you can see what the parent outputs on stdout on TTY and what you type on the keyboard is still received by the parent through stdin.

 (Using child_process.fork() for spawning child Node process as in your example is also a better practice, JFYI.)

In any event, do you understand why there may be cases where I want to use readline-Sync with its question and answer i/o channels reversed now?

**Comment by anseki** [comment]
Sorry, I can't understand your post perfectly, my English is no good.
Therefore I requested your sample code before.
Anyway, you can assign another stream to child's stdin/out very easily. Just specify it `stdio`. And if you want to get child's response absolutely, call `stream.end()` before it kills. By doing so, the parent get an event and read all data.
So, I asked you "do you want to use readlineSync in a child process?", and then is your answer "No"? I don't know you use readlineSync for what. You might want "Synchronous Process Execution" of Node, not readlineSync.

**Comment by tk44** [comment]
1. Please consider my code example is:
// Write to parent's STDIN, not child's STDIN.
stdin.write('Hello', function() { stdin.end(); });
// Read from parent's STDOUT, not child's STDOUT.
stdout.on('data', function(chunk) { res += chunk; });

2. I want to send a question to child process, and receive answer from child process, synchronously.

3. I know I have other options, but I want to use readline-sync in parent process to do this.

4. I do not want to reassign stdio of the parent.  And I do not want parent to access child.stdio directly.

5. Simply reversing stdin and stdout within readline-Sync will make this possible.

6. Current readline-Sync does not allow me to do this.

7. I am asking for adding an option to readline-Sync to do this.

**Comment by anseki** [comment]
Sorry, you may be feeling irritable, but I don't know what you want because I don't see your code.
I tried `process.stdin.write('Hello', function() { process.stdin.end(); });` as you said, but of course an error was thrown as I said, because that is not writable. If you executed the code completely, that code is different from above.
In the cases which use many child processes like httpd or Web crawler, the controller that is parent starts the children, and it sends/receives data via the streams that is not reversed. Therefore, those programs work without errors.

I can't understand "reversing stdin and stdout", because readlineSync assigns nothing. It just reads and writes via the streams (and TTY) assigned by caller, as usual programs. That is, the streams are chosen by you (caller), not readlineSync. Therefore I don't know how to change it.
If you absolutely can't show me your sample code, you show me example that accesses child.stdio *NOT* directly or reverses the streams, and I might understand it. Or rewrite code of readlineSync, and send me pull request please. I'll check that.

Anyway, I still think that [Synchronous Process Execution](http://nodejs.org/api/child_process.html#child_process_synchronous_process_creation) may help you, if you want to send to child and receive from child, synchronously.
Node 0.11+
```js
result = require('child_process').execSync('child-program');
console.log(result);
```

**Comment by anseki** [comment]
13 days have passed.
I think that this problem was already solved, and I close the issue.
If not solved, please reopen it.
