### ISSUE TITLE
feature request: option to output defaultInput

### ISSUE THREAD

**Issue by monsterkodi** [anseki/readline-sync#16]
Hello, 
it would be great if there would be an option to output the defaultInput in the 'answer area', e.g.:

> Your name?   john doe▮

The user would not only see what his input will be, but he could also modify it before pressing Enter.

thanks for the nice package,
yours monsterkodi

**Comment by anseki** [comment]
Hi monsterkodi, thank you for your post.
Yes, I also think your request is good. But, I think that it's very difficult in current Node...
Node doesn't support controlling the readline system library (e.g. like the bash). `stty` and emulation editable readline are needed (system calling or native add-on). And it has problems in Windows.

You can tell `defaultInput` to the user:

```js
input = readlineSync.question(
  'Your name? ${([)defaultInput(])} :',
  {defaultInput: 'john doe'}
);
```

But, the user has to input, if the user want another. (Not editing `defaultInput`)

**Comment by monsterkodi** [comment]
Hi anseki, thanks for your fast feedback.
I will try to something else then, I guess a similar effect should be possible with some ncurses hacking.

**Comment by anseki** [comment]
I see, you want TUI like the ncurses, then you may have to use something else like ncurses, because readlineSync is based on readline (CLI).
That is, I think that your idea may not be good about usability for CLI. I think that it should have the interface that is accustomed to use for many users. Almost all users don't notice that shown default-value is editable, because almost all CLI programs are readline style (uneditable default-value).
Then the users may just type a name at right side of `john doe` without removing it (i.e. the name `john doeanseki` is input), because the users don't have to remove default-value in almost all CLI programs.

**Comment by monsterkodi** [comment]
Thanks again for your feedback. Your usability concerns are probably valid, but they don't really apply in my case, since I don't intend to publish the project. But I understand now why it is not possible to implement the feature in readline-sync, so i will probably use ncurses instead. That doesn't mean that readline-sync isn't good enough, it's just not the right tool in my special case. I am sure I will use it in other projects in the future. Keep up the good work, yours monsterkodi

**Comment by anseki** [comment]
Yes, ncurses is better for TUI, and it's more easy than readlineSync. JavaScript binding, Node plugin, etc. are published. It will help you because it can handle escape sequence correctly on POSIX.
Thank you for your evaluation of readlineSync.
Well, this issue is closed?

**Comment by monsterkodi** [comment]
Yes, the issue should be closed.
Thanks again for your time and support.
