### ISSUE TITLE
no echo in REPL

### ISSUE THREAD

**Issue by markjreed** [anseki/readline-sync#20]
running readline-sync 1.2.21 on node 0.12.7 on OS X Yosemite.

If I run something that calls e.g. question() from the REPL, I get no echo while typing. In the regular node REPL, my echoed response shows up all at once after pressing the return key.  In the coffee REPL, it never gets echoed at all.

**Comment by anseki** [comment]
Hi markjreed, thank you for your post.

readlineSync tries read/write with TTY. And, as you know, also REPL reads and writes with TTY.
The any program that handles TTY doesn't work in REPL because REPL handles TTY. That is, it's like emulating the shell. readlineSync never block REPL.
This is not bug. This is design of nodejs. And, nobody will want to use readlineSync in REPL.

Try this code in REPL:

```js
process.stdin.pause()
```

If you want to read a line from another stream that is not REPL, you might have to assign another channel (e.g. remote connection `start({input: socket})`).
But, that idea is not good... Because the REPL is used for debug, that is a easy interactive environment. That will spoil REPL's good interactivity.
If you want to make the code run step by step for debug, the `node debug` might help you. Or, other debug tools like node-inspector.

**Comment by anseki** [comment]
There is no reply, and I close this issue.
If not solved, please reopen it.
