### ISSUE TITLE
it will block http request ?

### ISSUE THREAD

**Issue by linecheng** [anseki/readline-sync#21]
I want  create a tools to request server by  conversation with the user via a console. 
but found request is canot be send until  the loop completed.
code like this 

server
```
//main.js

var http = require("http");  
var i=0;
http.createServer(function(request, response) {  
    console.log('request received' + i );  
    response.writeHead(200, {"Content-Type": "text/html;charset=utf-8"}); 
	response.write(i.toString());
        response.end();  
	i++;
}).listen(9990);  
console.log('server started');  
```

client
```
// readline.js
// npm install readline-sync
// npm install request

var readline = require("readline-sync");
var request = require("request");

for (var i = 0; i < 10; i++) {

    var ans = readline.question("do requ ?");
    
    if (ans == "y") {
       console.log("begin to request");
       
        request("http://localhost:9990", function (err, resp, body) {

            console.log("get ->" + body);

        });
    }
}
```
exe processing:

left is server , right is client

The first four cycles , the server output nothing.
![1](https://cloud.githubusercontent.com/assets/1991282/10261887/b6fb805e-69e1-11e5-8bd6-eeac363abb16.png)

untill  ten times ,  server output  all things.
![2](https://cloud.githubusercontent.com/assets/1991282/10261888/c8084152-69e1-11e5-9346-9c244842d7a2.png)

i have two question 

1.   why not send request one by one ?
2.  how should to modified to  send  request after press y and enter ?

thanks very much

**Comment by anseki** [comment]
Hi linecheng, thank you for your post.

The matter is very simple. This is correct JavaScript behavior.

First, you must understand about JavaScript working.
JavaScript basically works in **single thread**. The event loop does not run unless you release the thread.
For example:

```js
setTimeout(function() {
  console.log('3 seconds?');
}, 3000);

var startTime = Date.now();
while (true) {
  if (Date.now() - startTime > 10000) {
    console.log('10 seconds');
    break;
  }
}
```

The code above and your code don't work by the same cause.
The callback you gave to `request` is executed at next event loop, but you don't release the thread until a `request` is called 10 times. The thread is released after that is called 10 times, and then, the callbacks are executed, and `request`s are finished.

Same result comes even if readlineSync is not used because this is JavaScript behavior.

```js
//var ans = readline.question("do requ ?");
var ans = 'y';
```

If you want to send a request per the user response, release the thread per calling the `request`.
For example:

```js
var readlineSync = require('readline-sync'),
  request = require('request'),
  count = 0;

function doRequest() {
  if (!readlineSync.keyInYN('Do request?')) { return; }
  console.log('begin to request');
  request('http://localhost:9990', function (err, resp, body) {
    console.log('get ->' + body);
    if (++count < 10) { doRequest(); }
  });
}

doRequest();
```

**Comment by linecheng** [comment]
anseki, 
   Thank you so much for your apply.
I have understond  **JavaScript basically works in single thread**.

**Comment by anseki** [comment]
Hi linecheng.
Did you post a comment? And did you close and reopen this again?
There is no reply... and I have no idea.
If you reopened this because you still have question, tell me it.
If this issue was solved, close it please. :smiley:

**Comment by linecheng** [comment]
anseki ,
   Thanks for your apply so much .
   sorry point the wrong button accidentally ....

I have understond  JavaScript basically works in single thread  ,  realized it was JavaScript behavior.

I can understand the callback will be called  after the thread is released . 

but how about the `request `? 
**even  `sending request`  will wait for  the released thread**  ? 

I have test with another code in chrome ,  the results seems like some differents between that code .

```
//reference jquery in current page 

for(var i=0;i<10;i++){
    console.log(i);
    $.get("http://localhost:9990",{},function(data){
       
       console.log(i+"--> get " + data);
        
    });
}
```

**when one loop executed,  the server got one request , and gaven response**. after 10 times , the thread is  released , the 10 callbacks are executed .

 According up  , I should get one request  on server   in one loop . 
but that code   `for (var i = 0; i < 10; i++) {   request (........)  }`   , No sending one request  in one loop.This is where I'm confused .

I don't know if I  express it clearly , thank you for your apply again .

**Comment by anseki** [comment]
That is very simple too.

Remember, JavaScript can **not** send the HTTP request oneself.
So, how did you send the HTTP request? Yes, you used the libraries.
That is, which library you used?
You used `request` module, and jQuery. Of course, the library decide when it send the request.

* `request` module sends the request when an event is fired. That is, in event loop that started after the thread was released from your code.
* jQuery sends the request immediately when `ajax` is called. That is, in your code of a loop. (the method sends the request, and it returns thread to your code.)

These are the behavior of libraries. Not JavaScript. (Many modules of Node that include `request` module are event-driven, because Node is event-driven. It's basic and big and important feature of Node.)

Try these 2 code:

```js
function like_request(cb) {
  setTimeout(function() {
    cb('DONE: like_request');
  }, 10);
}

for (var i = 0; i < 10; i++) {
  console.log(i);
  like_request(function(data){
    console.log(i + ' --> get ' + data);
  });
}
```

```js
function like_jQuery(cb) {
  // setTimeout(function() {
    cb('DONE: like_jQuery');
  // }, 10);
}

for (var i = 0; i < 10; i++) {
  console.log(i);
  like_jQuery(function(data){
    console.log(i + ' --> get ' + data);
  });
}
```

See 2 results, and difference of 2 codes.

BTW,
You can see the order of those steps easily by the Developer Tools of Chrome or others.
Press [F12] key to open the Developer Tools. And open "Sources" tab.
And then, you can make the code run step by step, by [F10], [F11] key, etc.. You get a time when the request is sent.

**Comment by linecheng** [comment]
anseki,

Thank you for your patience. 
 I understand  they are different between the two libraries now .
`request` module sends the request when an event is fired,   but the `jQuery` sends the request immediately.
I will learn more basic things of Node .

You have solved my confusing , thank you so much ,  I will close this  issue .

Thank you .  : )

**Comment by anseki** [comment]
I recommend you reading the official document always. There are many many unofficial documents, samples, etc. in the internet, but a official document will most help us.
For example, a document about your first question is [here](https://github.com/request/request/).
(explanation about the behavior of `request` module, information about the time when your callback is called, etc.)

The official document will let us avoid the problems, or it will let us solve the problems.

Enjoy coding! :smile:

**Comment by linecheng** [comment]
Ok, Thank you so much !

Yes, Enjoy coding! :smile:
