### ISSUE TITLE
Encounter [Device not configured] in Intellij Idea

### ISSUE THREAD

**Issue by minioreo** [anseki/readline-sync#23]
When I'm using Intellij Idea to run my node script，I got some error below：

node_modules/readline-sync/lib/read.sh: line 49: /dev/tty: Device not configured
Error: The platform doesn't support interactive reading
stty: /dev/tty: Device not configured

my code is simple：

    "use strict"
    let readlineSync = require("readline-sync");
    let username = "";
    while(username == ""){
        username = readlineSync.question('username:');
    }

This error won't happen when I'm using terminal to run node test.js.
But When I'm using idea IDE run,the error occured.

It will be ok when using nodejs native read-line when using Idea.

**Comment by anseki** [comment]
Hi minioreo, thank you for your post.

readlineSync has to throw an error when it can't access TTY, and of course that is a correct behavior, because readlineSync is a module to have a conversation with the user via TTY.
I think that you might have made it run in the debug console. Any program that uses TTY doesn't work fine unless it is started from TTY which is an interactive shell or an environment which can access to TTY.

So, what do you want to do? Are you writing an IntelliJ IDEA Plugin?
If you write something that has to run in IntelliJ IDEA with interactive UI, I think that you should use Java.

**Comment by anseki** [comment]
There is no reply, and I close this issue.
If not solved, please reopen it.
