### ISSUE TITLE
Running Debugger throws Error

### ISSUE THREAD

**Issue by marktyers** [anseki/readline-sync#25]
Script runs without errors until I try to run the **debugger** then immediately throws error:
```
enter command: bash: line 1: 10155 Segmentation fault      node --nocrankshaft --nolazy --nodead_code_elimination --debug-brk=15454 '/home/ubuntu/workspace/305CDE/02 Objects and Functions/shopping/index.js'                                                        

Process exited with code: 139
```

**Comment by anseki** [comment]
Hi marktyers, thank you for your report.

So, I need more information, version of Node.js, version of readlineSync, your environment (it seems ubuntu). And could you show me your code? Or, does that code load other modules?

But, it seems that this issue relates to some issues about segfault and debugger of Node.js that were recently reported.
e.g. 
https://github.com/nodejs/node/issues/4382
https://github.com/nodejs/node/issues/4322
https://github.com/nodejs/node/issues/4261

These were fixed in this PR:
https://github.com/nodejs/node/commit/25776f3ea14fb0aadae38ce91c2fbcfa95746255

**Comment by anseki** [comment]
There is no reply, and I close this issue.
If not solved, please reopen it.
