### ISSUE TITLE
rl.question isn't working on Git for Windows

### ISSUE THREAD

**Issue by jamesqo** [anseki/readline-sync#33]
Hi, thanks for making this great library. :smile:

I recently ran into a problem while using [Git for Windows](https://git-scm.com/download) (which uses the MSYS2/MinTTY shell if I recall correctly) to run my Node.js script. For some reason, when I run this code in that shell, which uses `question`:

```js
var rl = require('readline-sync');

function loginUser() {
    console.log('Please enter your GitHub credentials.');
    username = rl.question('Username: ');
    password = rl.question('Password: ', { hideEchoBack: true }); // don't echo for password
    saveCredentials(username, password);
}
```

then nothing actually happens. Instead of printing `Username: ` and then waiting for input, it looks like it just hangs there and won't respond no matter how many times Enter is pressed. When you finally Ctrl + C out of the process, it will flush out all of the input you had typed as if they were commands.

### Screenshot

![](http://i.imgur.com/grjs4he.png)

The repro script for this can be found here: https://github.com/jamesqo/git-delete

And yes, I tested and it seems to be working fine with regular old CMD.

**Comment by anseki** [comment]
Hi @jamesqo, thank you for your report.

As an experiment, insert this line before `readlineSync#question`, then try to run it:

```js
process.stdin.isTTY = process.stdout.isTTY = true;
```

For example, this code works fine in mintty:

```js
const readlineSync = require('readline-sync');
process.stdin.isTTY = process.stdout.isTTY = true;
var userName = readlineSync.question('May I have your name? :');
console.log(`Hi ${userName}!`);
```

**Note that this doesn't become a solution to the root of the problem even if your program works.**

Important points:
- Since readlineSync is a module to read/write TTY, of course it doesn't work in environment that has no TTY.
- mintty actually does **not** have TTY, it emulates TTY and it gives pseudo terminal device.

Run this command in mintty:

```
node -p -e "Boolean(process.stdout.isTTY)"
```

A result `false` means that it does not have TTY. This command will return `true` in Windows CMD.

Therefore, many interactive programs don't work in mintty. That is very well known.
See: http://mintty.googlecode.com/svn/branches/1.1/docs/mintty.1.html#29
https://github.com/nodejs/node/issues/3006

Also, there is a wrapper "winpty" to solve that:
https://code.google.com/archive/p/mintty/issues/56

Remember, overriding `process.std*.isTTY` is no good. At least you should use this way only when your program is called from command line directly.
So, readlineSync might not work completely. Some methods and options such as `hideEchoBack` might be not able to get raw-mode.
Then, usually mintty should be not used for interactive programs. If you don't like Windows CMD, you can try Console2, ConEmu, Cmder, etc. (I didn't check readlineSync in those yet.)

**Comment by anseki** [comment]
No reply came, and I close this issue.

**Comment by anseki** [comment]
Hi @chung-leong, thank you for the comment.

So, could you show me the script that has problem and the commands that ran the script? And your environment?
That is, the Node.js doesn't start via a shebang in Windows, as you said.

**Comment by chung-leong** [comment]
Here's the script:

https://github.com/chung-leong/trambar-cli/blob/master/bin/index.js

In normal usage, it's trigger by npm. Here's the line in package.json: 

https://github.com/chung-leong/trambar-cli/blob/master/package.json#L5

I was making changes to the script for Windows. When I ran `bin/index.js install` from within the Git bash  shell, the prompt wouldn't appear. It works when I do `node bin/index.js install`. For some reason, `process.stdout.isTTY` is undefined in the first case where as it's true in the second.

**Comment by anseki** [comment]
I see.
Since readlineSync is a module to read/write TTY, of course it doesn't work in environment that has no TTY.
See https://github.com/anseki/readline-sync/issues/33#issuecomment-212849534 .

That may work fine in CMD because NPM will set up the `PATH` for the `bin` field. Therefore you can execute this:
```
npm install trambar
trambar
```
The `trambar` command works fine.

**Comment by chung-leong** [comment]
Just realized why I was confused by this. I didn't know that "node" is aliases to "winpty node" in the Git bash shell:

```
$ node -p -e "Boolean(process.stdout.isTTY)"
true
```

```
$ node.exe -p -e "Boolean(process.stdout.isTTY)"
false
```

```
$ env node -p -e "Boolean(process.stdout.isTTY)"
false
```

**Comment by anseki** [comment]
Your script works fine via the `trambar` command without Git bash and winpty and a shebang.
See https://github.com/anseki/readline-sync/issues/33#issuecomment-387051826

**Comment by ZoWnX** [comment]
Adding 

`process.stdin.isTTY` = process.stdout.isTTY = true;

fixed it in gitbash for windows.
