### ISSUE TITLE
First answer sometimes must be preceded by ENTER

### ISSUE THREAD

**Issue by der-david** [anseki/readline-sync#37]
Unfortunately I have an issue on a Windows machine using node v5.10.1.

When asking the user the _first_ question, the answer will _sometimes_ only be accepted after pressing <kbd>⏎</kbd> once, then answering and (if required) pressing <kbd>⏎</kbd> again.

Taken from the examples:
```javascript
'use strict';
const readlineSync = require('readline-sync');
var userName = readlineSync.question('May I have your name? :');
console.log('Hi ' + userName + '!');
```

With limited input possibilities I can _often times_ write anything I want when prompted for the first time, then I press <kbd>⏎</kbd> and only then my input is filtered regarding the possible options.
```javascript
'use strict';
for (let i = 1; i <= 3; i++) {
  if (readlineSync.keyInYNStrict('What about ' + i + '?')) {
    console.log('yep');
  } else {
    console.log('nope');
  }
}
```

Any further answers are accepted correctly.

Without further investigation I assume this is related to the Windows terminal but unfortunately I am limited to this requirement.
Can anyone else confirm this issue, provide a simple workaround or fix the cause?

**Comment by anseki** [comment]
Hi @der-david, thank you for the report.

This issue is the same as issue-18.
This is a bug of Node.js (https://github.com/nodejs/node/issues/2504), and the bug was already fixed in v4.2.4 (LTS) and v5.1.0.
But, the bug seems to have been come again in v5.7.0, and then, it was already fixed again in v6.2.0.

An easy way to check whether a version of Node.js has this bug:

1. Start REPL (`node` command).
2. Input `1` and press Enter key.
3. Incorrect result:
```
> 1
1
1
>
```

Correct result:
```
> 1
1
>
```

Using current version or LTS of Node.js is recommended.
And I will add the versions of Node.js that have the bug to a list in readlineSync to avoid using a stream of Node.js.

**Comment by der-david** [comment]
Thanks for the quick reply!
I must have missed the issue due to the unspecific title.

Since upgrading shouldn't be a problem for me, I am fine with this solution :+1:

**Comment by anseki** [comment]
The versions of Node.js that have the bug were added to a list in readlineSync to avoid using a stream of Node.js.
