### ISSUE TITLE
Display defaultInput value to be edited

### ISSUE THREAD

**Issue by ecwyne** [anseki/readline-sync#46]
Thanks so much for the package! It's incredibly useful!

Is it possible to display the defaultInput to the user so that they can edit it as opposed to needing to type a brand new value?

For example:
```javascript
readlineSync.question('Please edit value: ', {defaultInput: 'DEFAULT_VALUE'})
```
```bash
Please edit value: DEFAULT_VALUE
```

My use case is as follows:
Inputs have a maximum length. If value.length > max then I want to prompt the user to shorten the input without having to retype the entire value.

**Comment by anseki** [comment]
Hi @ecwyne, thank you for the proposal and your evaluation of readlineSync.

I understand that the feature may be useful for users who was inured to GUI. And I examined it before, but I didn't implement it.
Because it's not common CLI style (it may not be good about usability for CLI). And also, I think that implementing it is difficult.
See https://github.com/anseki/readline-sync/issues/16.

I think that CLI (i.e. the readline style) is unsuitable for input very long text. It might be good to reconsider the interface of your program.
For example, a input text that contains multiple somethings should be input separately as possible, such as first-name and last-name.
Or, re-input only a part of text, such as a byte of IP address.
Or, write the text that should be edited to clipboard, and the user can paste it to edit it. Node.js modules allow access to clipboard (e.g. [node-copy-paste](https://github.com/xavi-/node-copy-paste)). *But, I think that this may be not good idea because it makes the user confuse, and also, almost all terminals have "Copy" and "Paste" commands.*
Or, you can use TUI library. Actually, the input style you requested is TUI.

**Comment by anseki** [comment]
No reply came, and I close this issue.
