### ISSUE TITLE
readline-sync cannot prompt in chinese

### ISSUE THREAD

**Issue by wangzhengbeijian** [anseki/readline-sync#48]
```js
const rls = require('readline-sync')
console.log('你好')
rls.question('你好')
```
results
```
λ node test.js
 你好
 浣犲ソ
```
I'm on I'm on windows 7, node 6.2.1.

**Comment by anseki** [comment]
Hi @wangzhengbeijian, thank you for the report.

ECMAScript (Node.JS) supports Unicode (i.e. Chinese characters), by default.
For example, I tried the following code that contains CJK characters (Chinese, Japanese and Korean characters).
(Note that the script file also should be saved with UTF-8 encoding.)

```js
const readlineSync = require('readline-sync');

console.log('ANSWER: ' + readlineSync.question('你好: '));
console.log('ANSWER: ' + readlineSync.question('こんにちは: '));
console.log('ANSWER: ' + readlineSync.question('안녕하세요: '));
```

Result:

```
你好: hello
ANSWER: hello
こんにちは: hello
ANSWER: hello
안녕하세요: hello
ANSWER: hello
```

You should configure your terminal to use Unicode (UTF-8) when you want to make Node.JS input/output, regardless of readlineSync. Only some APIs (such as `console`) emulate the locale encoding.
Otherwise those data need to be converted to/from the locale encoding (e.g. GBK ) in some way (e.g. iconv).

I think that you probably do not use Cmd.exe, a decent terminal such as [Cmder](http://cmder.net/) should be used instead of Cmd.exe that has many problems, as everyone knows.
Anyway, I show how to configure Cmd.exe, for your information.

Get current code page for when you want to change it to the origin. The current code page is shown by the following command.
```
chcp
```
And, change the code page to UTF-8.
```
chcp 65001
```

You can change the font by "Properties" dialog box of Cmd.exe that is shown by clicking the upper-left corner of the window, and then clicking "Properties".
But a font that supports Unicode might not be shown in the font list. You can add fonts by the following:

1. Start `regedit` and open `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\TrueTypeFont`.
2. Add new `REG_SZ` (string) named `65001` (or `65001.1` if `65001` already exists), and specify the font name you want to use for the value.
3. Restart Windows, and change the font in the "Properties" dialog box.

**Comment by wangzhengbeijian** [comment]
I do use cmder, and ```chcp 65001``` solve my problem.
Thank you so much.
