### ISSUE TITLE
Browser module

### ISSUE THREAD

**Issue by jsejcksn** [anseki/readline-sync#49]
Is it possible to use this as a browser module or does it exclusively rely on OS-specific TTY implementations for input?

**Comment by anseki** [comment]
Hi @jsejcksn, thank you for the comment.

If something that emulates TTY precisely in a web browser is bound, readlineSync might work with that. But I can't conceive a case where it is required in a web browser. And I have never tried that.
Are you making a terminal emulator that works in web browser?

**Comment by jsejcksn** [comment]
@anseki Not exactly an emulator, but maybe you could call it an _impersonator_? 😏 The beginning of my project is at [jsejcksn/prompt](//github.com/jsejcksn/prompt).

**Comment by anseki** [comment]
I see. It seems to have UI like TTY, same as a terminal emulator, anyway.
And I think that readlineSync is not required for your app because it already can get the user input via DOM and its events.
Sorry, I can't understand yet what you want to let readlineSync do. This is a module to do "readline". The your app seems to use key-events instead of "readline".

**Comment by jsejcksn** [comment]
I thought it might possibly allow me to have synchronous interactions in the browser.

**Comment by anseki** [comment]
readlineSync is a module to do "readline".
I think that readlineSync is not required for your app.
DOM works in event-driven model. Therefore, the synchronous execution is unneeded, and the event-loop should be not blocked.
If the app works in Node.js with DOM like Electron, it may be able to do synchronous execution. It supports the Synchronous Process Execution.
But it's better that the your app doesn't block the event-loop.
If you want to get user input easily without callback, you can use thenable Promise object.

**Comment by jsejcksn** [comment]
Thank you for your feedback. I haven't gotten very far into my project yet so I'll research Promises more as I continue.

Thank you also for taking time to look at my project and discuss with me. You can close this issue.

**Comment by anseki** [comment]
I'm glad if those information helped you.
BTW, your app seems not to work in some web browsers because it uses `window.event` that is not standard. I recommend using an event object that is passed via argument of the event listener instead.
https://developer.mozilla.org/en-US/docs/Web/API/Window/event

**Comment by jsejcksn** [comment]
Thanks. I didn't understand how that worked before, but now I do!
