### ISSUE TITLE
Can keyIn accept \r?

### ISSUE THREAD

**Issue by DanielJohnBenton** [anseki/readline-sync#51]
I noticed that keyIn does not react when I hit the `enter` key. Is there an option to allow this to be entered as a character?

It appears that the default limit is `[]` and keepWhitespace does not apply.

Fantastic library by the way thanks a lot.

**Comment by DanielJohnBenton** [comment]
I suspect the issue is on this line `if (chunk && typeof (line = (chunk.match(/^(.*?)[\r\n]/) || [])[1]) === 'string') {`

because if I do: `console.log(JSON.stringify(chunk.match(/^(.*?)[\r\n]/)));` directly above it, I get ["\r", ""] meaning index [1] is a blank string, so the loop won't exit for `\r`

(`_readlineSync`)

**Comment by anseki** [comment]
Hi @DanielJohnBenton, thank you for the comment.

That is correct behavior.
Unlike `question*` methods, `keyIn*` methods should not accept Enter key because these are provided to get the input without Enter key.
https://github.com/anseki/readline-sync#keyin
Use `question*` methods or `prompt*` methods that accept Enter key.
For example, if you want to wait until the user presses Enter key:

```js
readlineSync.question('Hit Enter key to continue.', {hideEchoBack: true, mask: ''});
```

BTW, a type of the blank string also is `string`.

**Comment by DanielJohnBenton** [comment]
Thanks for your response @aneksi.

I assumed this was a bug because I have not seen any prompts (like in the examples in README.md) that say "hit any key" and then ignore the enter key - and this limitation is not documented.

I respect your choice not to support `\r` as a value for `keyIn` however it does not suit my requirements so I will probably use my fork going forward.

I have been tearing my hair out trying to find a synchronous way to mimic the behaviour of C's `getch`. Your library with my fix works just fine for this requirement, at least on Windows.

Thanks again for the library, I have been looking for something like this for a while and it's very well made.

**Comment by anseki** [comment]
Thank you for the evaluation.

As you said, many control keys (not only Enter, <kbd>F1</kbd>, <kbd>DEL</kbd>, <kbd>ESC</kbd>, etc.) are not accepted.
I thought that is tacit understanding, but I will consider updating the document. Thank you.

Your code might work only now in your environment, but there is small misunderstanding.
As I said, a blank string (`''`) also is `string`, therefore `typeof ["\r", ""][1] === 'string'` is `true`, then, it does not forbid exiting the loop.
The code that forbids exiting the loop is `input.length >= reqSize`. The length of `input` is zero because `\r` and `\n` are removed.
Also, `atEol = true` is unnecessary because `atEol` is never used.

So, I close this issue. Please re-open if you need. Thank you 😃

**Comment by DanielJohnBenton** [comment]
Ah, you're right, somehow misread `!options.keyIn && atEol` as `options.keyIn && atEol`.

So the real issue was at `chunk = line;`, where `chunk` is set to a blank string.

No need to re-open, I found my fix.
