### ISSUE TITLE
Accept enter key in keyInPause.

### ISSUE THREAD

**Issue by sant123** [anseki/readline-sync#52]
It seems keyInPause does nothing if enter key is pressed. 

`By default, any key is accepted. You can change this behavior by specifying limit option (e.g. accept only a Space Bar).`

Thank you!

**Comment by anseki** [comment]
Hi @sant123, thank you for the comment.

That is correct behavior.
Unlike `question*` methods, `keyIn*` methods should not accept Enter key because these are provided to get the input without Enter key.
https://github.com/anseki/readline-sync#keyin
If you want to wait until the user presses Enter key, try this:

```js
readlineSync.question('Hit Enter key to continue.', {hideEchoBack: true, mask: ''});
```

**Comment by sant123** [comment]
Hi @anseki, thank you for the answer.

But if I want to listen to any key including enter? I mean, press any key to continue? What should I do there?

Thank you!

**Comment by anseki** [comment]
Current version of readlineSync can not accept that.
But I think that is unnecessary, I feel that is strange UI. Typically control keys (**not only Enter**, <kbd>F1</kbd>, <kbd>DEL</kbd>, <kbd>ESC</kbd>, etc.) are not accepted, and users also understand that.
Also, it can not get all key input.

**Comment by sant123** [comment]
Yes it has sense, but if you tell a user to press any key to continue; they'd normally press enter key. As I say, the traditional message... "Press any key to continue".

**Comment by DanielJohnBenton** [comment]
I agree that the traditional response to "press any key" is to hit Enter or Space, and many such prompts I have encountered respond to this. An example being CMD which says "Press any key to continue . . ." and responds to Enter.

Additionally, there may be use cases (such as mine proposed earlier, mimicking C's `getch` function) where the fact that the user hit enter is useful input data.

It sounds like you have found these to be edge use cases for the library however. I am not trying to argue this, just that "strange UI" is an unfair classification.

**Comment by sant123** [comment]
Thank you @DanielJohnBenton 😄

**Comment by anseki** [comment]
Thank you for the opinion.
Anyway, as I said, current version of readlineSync can not get many control keys.
Then, please use another library to do that.
Maybe, I have to write addon (not module) in another language because the reading those is hard for Node.JS and the readline API depends on each environment very much, as everyone may know.
But I want to make readlineSync keep being "No Dependency" library.
I might write that someday, but you'd better use another library.

**Comment by anseki** [comment]
Or, you can use `Readline` module to get input Enter key.
This may be easiest way.

**Comment by sant123** [comment]
Thank you @anseki!

**Comment by anseki** [comment]
😄 

I close this issue. Please reopen if you need.
