### ISSUE TITLE
cp866 support for non-utf8 terminals

### ISSUE THREAD

**Issue by Guevara-chan** [anseki/readline-sync#54]
**Where do we stand:** so far it's not possible to properly read or write utf8-encoded cyrillic letters to older Windows terminals (even Win10 one with classic mode enabled) - results being garbage. While I was able to [monkey patch](https://gist.github.com/Guevara-chan/4f0dd72736bed52a4cfbfd2eead1ffaf) this issue using _iconv-lite_, it's not like hacks could ever make a proper solution.

Just try some cyrillics in those code **without** my fixes:
```
var rl = require('readline-sync');
var user_name = rl.question("Как вас зовут ? ");
console.log("Hello, " + user_name + " !");
```

**What could be done:** I guess, some internal translation proc could be used for older Windows systems, probably one from _iconv-lite_ mentioned above.

**Comment by anseki** [comment]
Hi @Guevara-chan, thank you for the comment.

I know that issue, and that is an issue about Node.js and `CMD.exe`, not readlineSync.
For example, `console.log` also can't output non-UTF8 characters to TTY in CMD, especially output of external commands.
Therefore those have to be converted like `console.log(iconv.decode(data, 'CODE'))` in your code regardless of readlineSync.
Or, your code calls the `chcp 65001` command of CMD before doing something. Then CMD supports UTF8.

**Comment by Guevara-chan** [comment]
You are a little wrong here, actually. I'm not so sure about previous Node versions, yet here, on v6, `console.log` works perfectly with cyrillics. Problem only exists for direct terminal read\write attempts, especially since _readline-sync_ does not currently support _Buffers_ as 'query' argument, neither it allows to receive one as input result.

**Comment by anseki** [comment]
The `console.log` does not work perfectly yet with non-UTF8 (not only cyrillic), in Node.js v6 and v7.
Anyways, readlineSync accepts Buffer also, but only `toString()` is called to output it, and the converting data that is read by PowerShell may not be easy.
Then, `chcp` may be the simplest way to solve.

**Comment by Guevara-chan** [comment]
> The console.log does not work perfectly yet with non-UTF8 (not only cyrillic), in Node.js v6 and v7.

Hm... Just checked it for you (standart CoffeeScript interpeter from _NPM_)
![image](https://cloud.githubusercontent.com/assets/8768470/23278954/6376fd12-fa24-11e6-8697-3a1be0b92c8f.png)

>Anyways, readlineSync accepts Buffer also

Well, unfortunately, your code seems to only write first **0** bytes of buffered _query_/_display.options_ to _fdW_ due to missing fourth parameter (**length**):
```
    if (options.display) {
      fs.writeSync(fdW, options.display);
      options.display = '';
    }
```
(reason I was forced to emulate it for my patch)

Now, as for returned values, something like _questionBuffer_ forked function may be a way here.

**Comment by anseki** [comment]
As I said, the non-UTF8 is not only cyrillic. I am not trying to argue it, but your test is too simple. It's far from "perfect".
And also, as I said, those arguments for a Buffer do not have to be passed to the `writeSync` method because the `options.display` is already converted to a string. Those are silently ignored.
And also, as I said, unfortunately, your patch does not work in various environments and situations because readlineSync tries to output it by multiple ways. For example, it has to exchange the data with PowerShell.
Last year, I already tried to make it output a Buffer directly, and of course I added those arguments for `writeSync`, and I removed those.

Anyways, I might rewrite readlineSync in future version to support the outputting a Buffer directly, but it may be big changing. At the moment, it is in low demand.
If you really need it now, you'd better consider `chcp` or `Readline` module instead.
Or, your customized code might work in only your environment and situation.

**Comment by Guevara-chan** [comment]
Well, not trying to argue, but `chchp 65001` seems to do no good here. Let's do some quick test here (_'test.js'_):
```
var exec = require('child_process').exec;
exec("chcp 65001");

var rl = require('readline-sync');
var user_name = rl.question("Как вас зовут ? ");
console.log("Hello, " + user_name + " !");
```
...a~nd here we go:
![image](https://cloud.githubusercontent.com/assets/8768470/23292307/ea7e1f2a-fa6f-11e6-87b8-4d5cb93f4760.png)
(doesn't even seems to echo any cyrillic input here).

> Last year, I already tried to make it output a Buffer directly, and of course I added those arguments for writeSync, and I removed those.

Sad to hear these. Seems like my situation is really specific to current environment (localized Win10, classic console mode).

**Comment by anseki** [comment]
It seems that there are two mistakes.

- `child_process.exec` works in asynchronous mode. That should be output within the `callback` or use `child_process.execSync` method instead.
- It seems that you are using a font that does not support UTF8. You can specify a font by a property panel.

For example:

```js
require('child_process').exec('chcp 65001', () =>
  console.log('Hello, ' + require('readline-sync').question('Как вас зовут ? ') + ' !');
```

Result:
![ss01](https://cloud.githubusercontent.com/assets/4763469/23294427/c5955f68-faae-11e6-8b32-886842e17342.png)

Or, `Readline` might be better for you. (because, as everyone knows, CMD has other problems also about fonts.)

Sorry that you sad. But readlineSync should work in various environments and situations as much as possible.
And you can use `chcp` or `Readline` module instead.
Or, your patch is not necessary if it only output before `readlineSync.question`.
If the `console.log` works "perfectly" in your environment, just use that instead of the `query` argument to output it.

```js
console.log(query); // fs.writeSync also can be used
answer = readlineSync.question();
```

**Comment by Guevara-chan** [comment]
> `child_process.exec` works in asynchronous mode.
Oh, thank you for catching it ! Not that it matters much, since `chcp` finishes before user will ever have a chance to input anything, but still. Now, with 'Lucida Console' 12 things got a little better:
![image](https://cloud.githubusercontent.com/assets/8768470/23294871/9f2b397c-fa7e-11e6-8d9b-5fa09f5703d1.png)
...So, it's only return value from _question_ is missing. questionBuffer sounds for me like a plan even more now.

`If the console.log works "perfectly" in your environment, just use that instead of the query argument to output it.`

Trailing newline was a problem. On other hand, there arestill  'process.stdout.write', which I almost forgot about with all those 'con' devices ! Patched this into my fix code already, thank you for reminding me.

**Comment by anseki** [comment]
Use callback to catch an error.

I guessed that you are writing something that yourself use it, and that is not published, right?
I think that you already know, the best solution is to avoid CMD.
When do something in Windows, developers use a decent terminal such as Cmder instead of CMD that has many problems, as everyone knows.

**Comment by anseki** [comment]
So, was this issue finished?

**Comment by Guevara-chan** [comment]
> I guessed that you are writing something that yourself use it, and that is not published, right?
Yes, right. Was looking for good replacement to `node-clr`, since using _.NET_ just for `System.Console.ReadLine()` is suboptimal.
(not so sure about it now, though)

**Comment by anseki** [comment]
😄
