### ISSUE TITLE
error rendering emojis

### ISSUE THREAD

**Issue by akinozgen** [anseki/readline-sync#61]
Node: 8.5.0

usage: `givenUsername = readlineSync.question('❓ Your username: ');`

output: `ÔØô Your username:`

**Comment by anseki** [comment]
Hi @akinozgen, thank you for the comment.

It seems that your terminal failed to show the character because readlineSync only passes the specified string to the terminal.
For example, if you write the code with Unicode, your terminal should support Unicode.
If your environment (not readlineSync) does not support those characters (e.g. you use Windows), you should use a decent terminal such as [Cmder](http://cmder.net/) instead.

See https://github.com/anseki/readline-sync/issues/58.

**Comment by anseki** [comment]
No reply came, and I close this issue.
