### ISSUE TITLE
keyIn ignores limit

### ISSUE THREAD

**Issue by martinp999** [anseki/readline-sync#66]
var opts = {limit: function(input){return false;}};
var response = readline-sync.keyIn("blah", opts);

happily accepts any input

**Comment by anseki** [comment]
Hi @martinp999, thank you for the comment.

As the document indicates, `limit` option for `keyIn` method doesn't accept a function.
https://github.com/anseki/readline-sync#for-keyin-method
It should be like:

```js
// Accept only A, B or C
var readlineSync = require('readline-sync'),
  response = readlineSync.keyIn('Press a key', {limit: 'abc'});
console.log(`INPUT: ${response}`);
```

**Comment by martinp999** [comment]
Ahhh... ok, now that you point it out I've found it in the doco.  Perhaps you could put a small comment earlier in the "limit" section to refer further down for specific keyIn behaviour.

Btw, love the module but it's a shame keyIn behaves like this, otherwise it's exactly like question except for the fact that you don't have to press enter.

My requirement won't work with the simple filter, so I had to put a wrapper around keyIn to manage the filter myself.

**Comment by anseki** [comment]
Thank you for your suggestion.
In fact, the `limit` option for the `keyIn` method is just a convenient helper, and the `keyIn` method doesn't need the `limit` option because it works without an Enter key.
That is, it can work behind users completely, and this means that you can do anything with key input. Of course the `limit` **function** you want too.

I think that unneeded functions should not be added to readlineSync any more.
