### ISSUE TITLE
Exit Script?

### ISSUE THREAD

**Issue by gkoberger** [anseki/readline-sync#7]
Awesome project.

If the script is prompting using readline-sync, how does one exist the script? Ctrl+C doesn't seem to be working.

Thanks!

**Comment by Globegitter** [comment]
I am running into this issue now with iojs 1.5.1 on Mac OSX. I do have some packages that listen to `SIGINT`, such as mocha, but that should not interfere. Anything else that could interfere? Or any other way to debug this?

**Comment by gkoberger** [comment]
For me, the package that was causing the issue was Phantom. Hope that helps anyone else who gets stuck.

**Comment by anseki** [comment]
Hi Globegitter, Thank you for your post.
readlineSync throw an error when it caught signal.
And, I added more informations to the error object in v0.7.9.
```js
var readlineSync = require('readline-sync');

process.on('SIGINT', function() {
  console.log('\nI caught SIGINT signal.');
  process.exit();
});

process.on('SIGTERM', function() {
  console.log('\nI caught SIGTERM signal.');
  process.exit();
});

try {
  console.log('\nANSWER :' + readlineSync.question('Input text :'));
} catch (e) {
  if (e.signal === 'SIGINT' || e.signal === 'SIGTERM' ||
      // STATUS_CONTROL_C_EXIT: 0xC000013A
      e.exitCode === -1073741510 || e.exitCode === 3221225786) {
    console.log('\nreadlineSync caught signal.');
    setTimeout(function() { process.kill(process.pid, 'SIGINT'); }, 0);
  } else {
    console.error(e);
    process.exit(1);
  }
}
```

Then, Node v10- on *nix doesn't seem to get SIGINT and SIGTERM when it's reading TTY. SIGTSTP (^Z) works.
Node v11+ on *nix using shell, SIGINT works without error.
But, some shells in raw mode might send no-signal, it get ^C as code, not signal.
The both versions and shell and non-shell on Windows, SIGINT works.

I think that it's difficult because it comes from different platforms.
The error handling might help you, but it's not complete. Someday, Node might solve this problem.
Now, better way I think is giving the choice to cancel to user without ^C. e.g. input the empty string to cancel.

**Comment by monsterkodi** [comment]
I just discovered that the signal is swallowed on Mac OS X if the password mode is used:

```coffeescript
ask = require 'readline-sync'
ask.question 'password?', hideEchoBack: true
```
the above can't be canceled with Ctrl+C

**Comment by anseki** [comment]
Hi monsterkodi, thank you for your post.
That occurs on some versions of Node and external program. When your Node doesn't support raw mode TTY for `hideEchoBack`, readlineSync tries to use sehll. Those might ignore the signals regardless of readlineSync. e.g. in some cases, shell scripts also ignore the signals when reading line.
Give a way to cancel to user without the signals, if it's needed.
