### ISSUE TITLE
Does not works from Windows\Webstorm

### ISSUE THREAD

**Issue by ujja** [anseki/readline-sync#75]
Windows+ Webstorm + Node v10.13.0:

Toolbox\apps\WebStorm\ch-0\182.5107.19\bin\runnerw.exe[17120]: src\node_file.cc:1599: Assertion `args[1]->IsInt32()' failed.
 1: 000000013FEFECE5 
 2: 000000013FED8196 
 3: 000000013FED8261 
 4: 000000013FE9D557 
 5: 0000000140702E52 
 6: 00000001407042ED 
 7: 0000000140703349 
 8: 000000014070322B 
 9: 000003183765C5C1 

but works from command line.

Hint earlier I used [keypress](https://www.npmjs.com/package/keypress) it worked from Webstorm, but It blocked exiting my program

**Comment by anseki** [comment]
Hi @ujja, thank you for the comment.
So, do you mean that you executed a command in the terminal that was opened from WebStorm?
And, what is the terminal? i.e. What did you specify as terminal in WebStorm?
Also, could you show the command?

**Comment by ujja** [comment]
Hello @anseki,

If I use the webstorm terminal, and start "per hand", then it works. But if I start it in debug mode, then it does not work.

**Comment by anseki** [comment]
I see.
It seems that you called readlineSync in the environment that has no TTY, or TTY is disabled in the environment.
Since readlineSync is a module to read/write TTY, of course it doesn't work in environment that has no TTY.
See document: https://github.com/anseki/readline-sync
Therefore the error should be thrown, and that is correct and expected behavior.

**Comment by ujja** [comment]
ok, thank you!

**Comment by anseki** [comment]
:smile:
