### ISSUE TITLE
Crash when running with Nodemon

### ISSUE THREAD

**Issue by JakeMadsen** [anseki/readline-sync#77]
I simply get this error when trying to run my `.js` file with nodemon:

```
[nodemon] starting `node ./bin/server/launch.js`
npm[13932]: src\node_file.cc:1599: Assertion `args[1]->IsInt32()' failed.
 1: 00007FF7C71CACB5
 2: 00007FF7C71A44E6
 3: 00007FF7C71A45B1
 4: 00007FF7C716C277
 5: 00007FF7C79C33A2
 6: 00007FF7C79C480D
 7: 00007FF7C79C3899
 8: 00007FF7C79C377B
 9: 000000B3BA65C5C1
[nodemon] app crashed - waiting for file changes before starting...
```
if i try to run with node everything works as it should.

This is the piece of code crashing the application:

```js
console.log('Default server name is ' + serverSettings.serverName);
 let serverName = readlineSync.question('Choose name for server: ');
```

**Comment by anseki** [comment]
Hi @JakeMadsen, thank you for the comment.

readlineSync doesn't work in the environment without TTY because that is a library to read/write the TTY.
See document: https://github.com/anseki/readline-sync

BTW, I fixed strange format of your comment, you maybe mistook.

**Comment by JakeMadsen** [comment]
Thanks for the fast response @anseki and also thanks for fixing the format, it was teasing me so i gave up on making it look pretty. 

Is there a way to make it work with nodemon at all? It is somewhat faster to work with nodemon. 

If not i guess i will go on an adventure to try and find a solution to fixing it ^^

**Comment by anseki** [comment]
Of course the readlineSync can be used with the Nodemon.
Since you did not indicate your code or the purpose of using the readlineSync, these are typical cases:

- Use `--no-stdin` argument in the command line.  
For example: `nodemon --no-stdin "path/to/app.js"`
- Use readlineSync in a launch-script, and the launch-script starts the Nodemon.  
You can use the Nodemon without command line very easily. For example, you can get the object by `require('nodemon')`, and you can use methods and properties of that in your code.  
Or, you can also use the Nodemon as a child process. You can get the object by `require('child_process')`, and you can start the Nodemon in your code.  
Note that the launch-script has to be started with Node.js instead of Nodemon.

**Comment by anseki** [comment]
No reply came, then I close this issue. :cry:
