### ISSUE TITLE
Locked keyboard on docker

### ISSUE THREAD

**Issue by TauanMatos** [anseki/readline-sync#78]
Hi,

I created a simple script that reads the user input and created a docker container for it. But when I run my container with the -t flag my keyboard gets locked. I can't type anything. Does anybody know how to solve this?

**Comment by anseki** [comment]
Hi @TauanMatos, thank you for your comment.

Since readlineSync is a module to read/write TTY, of course it doesn't work in environment that has no TTY.
See document: https://github.com/anseki/readline-sync

The `-t` option to "Allocate a pseudo-TTY".
See document: https://docs.docker.com/v17.09/engine/reference/commandline/run/

**Comment by TauanMatos** [comment]
Using -it flag instead of -t works fine.

**Comment by anseki** [comment]
:smile:
