### ISSUE TITLE
Clear keyIn buffer

### ISSUE THREAD

**Issue by Eshake1000** [anseki/readline-sync#89]
I'm making console game that writes text char by char with delay of 10ms, and on next text line it waits for user to press space.

```javascript
for (let i = 0; i < location.Text.length; i += 1) { // Text loop
  const txt = location.Text[i];
  await writeDelay(txt, config.WritingDelay); // Async function that writes string char by char,  WritingDelay = 10
  rl.keyIn('', { hideEchoBack: true, mask: '', limit: config.WaitingKey }); // WaitingKey = Space
}
```

It works okay, but when I press space many times when text is writing, keyIn is ignored.
It seems like keyIn takes buffered input.

In C# I could empty input buffer with this: 
```c#
while (Console.KeyAvailable)
{
Console.ReadKey(true);
}
```
Is there any way to make keyIn ignore buffered input?

**Comment by anseki** [comment]
Hi @Eshake1000, thank you for the comment.
Since the buffer depends on environment, it is not easy.
I think that an easy way is that `writeDelay` checks the time between current calling and previous calling. That works like [lodash's `throttle` function](https://lodash.com/docs#throttle).
Or, consider using "Readline" module (not "readlineSync") instead.

BTW, you can use [`keyInPause`](https://github.com/anseki/readline-sync#utility_methods-keyinpause) instead of `keyIn`.
```js
rl.keyInPause('', {limit: config.WaitingKey})
```

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.

**Comment by anseki** [comment]
FYI;

```js
const readlineSync = require('readline-sync'),
  location = {Text: 'lorem ipsum'},
  config = {WritingDelay: 10, WaitingKey: ' '};

let lastWrote = 0; // Or `Date.now()` for delaying 1st char too.

for (let i = 0; i < location.Text.length;) { // Text loop
  readlineSync.keyInPause('', {limit: config.WaitingKey});
  const now = Date.now();
  if (now - lastWrote >= config.WritingDelay) {
    process.stdout.write(location.Text[i]);
    i++;
    lastWrote = now;
  }
}
```

Note:
+ Your code prints only first character immediately. This example improved it.
+ Your code pauses after last character was printed also. This example improved it.
+ This example delays key-in since second character.
