### ISSUE TITLE
readline-sync does not print special/unicode chars, bu tusing normal console.log() works fine

### ISSUE THREAD

**Issue by lukaarma** [anseki/readline-sync#93]
As per title if I give keyInSelect() an array containig some unicode/special chars it will mess them up, but if i use console.log on the same array it prints just fine.

Is this still a console encoding issue as many others on here or there's something more?

running windows10, powershell 5.1.18362.752

**Comment by anseki** [comment]
Hi @lukaarma, thank you for the comment.
These may help you:
https://github.com/anseki/readline-sync/issues/48
https://github.com/anseki/readline-sync/issues?q=is%3Aissue+encoding
This is a problem on only Windows.
If the issue is not solved by using another terminal instead, you had better use another library for prompt instead because it is dependent on environment.

**Comment by anseki** [comment]
No reply came, then this abandoned issue is closed.
