### ISSUE TITLE
Adding a default answer option to keyInYN*

### ISSUE THREAD

**Issue by drinking-code** [anseki/readline-sync#97]
I noticed that the Yes / No methods `keyInYN` and `keyInYNStrict` don't have an option to set a default answer, although it is common to have that in a CLI prompt to confirm. I'd like to propose to implement this option, perhaps like this:

The option `default` would have a default value of `null` which makes the two functions behave like they currently do. However, if the option lets say for `keyInYN` is set to `true` (or `"yes"`), the guide would change to display `[Y/n]` and the function would accept any key (in this case also the return key) as a _yes_ answer and only the [N] key as a _no_. Analogously, if the option is set to `false` (or `"no"`), the guide changes to `[y/N]`, every key (including return) pressed is read as a _no_, and only the [Y] key as a _yes_.

The return key would (like it currently does) not be accepted as an answer when the `default` option is not set, or set to `null`, but only if the `default` option is set to `true` or `false` (`"yes"` or `"no"`)

**Comment by anseki** [comment]
Hi @drinking-code, thank you for the comment.

readlineSync already supports the `''` for default processing.
You should find the example for default "Yes" and the example for default "No" in the document.
https://github.com/anseki/readline-sync#utility_methods-keyinyn
BTW, `keyIn*` methods don't require the Return key.

**Comment by drinking-code** [comment]
Yes.
I mean: a common way to respond to a prompt to confirm is pressing the return key, choosing the default option. I don't know if that's strictly against the principle of `keyIn*` but it would be nice to give the user the option to press return (choosing the default option).

An example in practice would be when removing a folder `rm -rf ./xyz/` sometimes you'll get asked
`rm: remove write-protected regular file ‘somefile’? [y/N]`. Pressing return results in a "no" response in this case.

**Comment by anseki** [comment]
Sorry, my English is poor.
Do you mean that you want to accept the Enter key?
If so, use `question*` method instead.
Unlike `question*` methods, `keyIn*` methods should not accept Enter key because these are provided to get the input without Enter key.
https://github.com/anseki/readline-sync#keyin
If you want to wait until the user presses Enter key, try this:

```js
readlineSync.question('Hit Enter key to continue.', {hideEchoBack: true, mask: ''});
```

**Comment by drinking-code** [comment]
Well, the `qusestion*` methods return only when the return key is pressed.  
The `keyIn*` methods return only when a letter key (and not the return key) is pressed.  
My proposal refers to a function/method that returns when either a letter key OR the return key is pressed.  
That function could be a completely new one, but I would suggest implementing this into the `keyIn*`.  

What I mean specifically is: a function that returns when either the [Y] key, the [N] key, or the return key is pressed.  
For example: `readlineSync.keyInYN('Are you sure?', {default: true});`. That would print as
```
Are you sure? [Y/n] 
```
pressing the [Y] key would make the function return `true`, pressing [N] would make it return `false` (just like the current `keyInYN*` methods). And pressing the return key would make the function return `true`, because that is set as the default.

**Comment by anseki** [comment]
Thank you for your proposal.
I think that the option should not be implemented into the `keyIn*` methods because these are provided to get the input without <kbd>Enter</kbd> key. That may make confusion.
More common behavior of CLI is that pressing <kbd>Y</kbd> / <kbd>N</kbd> key and <kbd>Enter</kbd> key.
If you really want to accept only single key including <kbd>Enter</kbd> key, use "Readline" module instead of "readlineSync".
